### ISSUE TITLE
Zone files are created improperly 

### ISSUE THREAD

**Issue by clickwir** [pdav/netmagis#156]
New install of netmagis and I'm new to using it. Ubuntu server. However, in my syslog I kept seeing errors for the zone files. Might be best explained by an example. 

cat test.local
;
; Zone test.local
;
; History
;   2016/02/19 : matt  : netmagis se
;
test.local.     IN      SOA     netmagis.test.local. 2016021907 (
                        86403
                        3600
                        3600000
                        86400
                        10800 )
;
; default TTL of RR
;
$ttl 86400
$ttl 86400
;
; Authoritative nameservers
;

                IN      NS      netmagis.test.local.
netmagis                IN      A       10.235.128.5
vr8vmware               IN      A       10.235.128.50

That last "10800 )" entry is for Negative Cache Time. Netmagis doesn't seem to include that or I've messed up something. As soon as I add that line, named no longer complains and loads the zone file ok.

**Comment by clickwir** [comment]
Ok, so I found that my zones file in the webui needed to be fixed. Is there no checking and reporting of that? It just assumes I know what BIND wants today and feeds it?

**Comment by pdav** [comment]
You're right: there is no syntax check (nor for DHCP). In order to include such checks, we should either code a zone parser (too complex for the expected gain) or include dependancies for the www package (i.e. require a BIND server on the Web server). So, we adopt a simple rule: the user knows what (s)he is doing...
